### PR TITLE
Added two buttons, configurable keyboard shortcuts and French translation.

### PR DESCRIPTION
**Pull request by R0maric**
Added two buttons (Play/Pause and Smart Pause). 
French translation.
Configurable keyboard shortcuts for Play/Pause and Smart Pause.

### CODE REVIEW

**Comment by DanielKamkha** [comment]
Great contribution, thanks! I'll test it soon, but just from the code it looks good.

**Comment by R0maric** [comment]
Thank you!
I added a function to (Play / Pause) by clicking on the favicon, and the ability to change the color of the tab.

**Comment by DanielKamkha** [comment]
Could you please submit "favicon and color" as a separate pull request? I think it requires some improvement and I would like to review it thoroughly. The rest of stuff look fine and could go in as it is.

**Comment by R0maric** [comment]
I do not know much about GitHub, but I think it's good.

**Comment by DanielKamkha** [comment]
I've tested and reviewed the changes. There are two issues.

First, the change for youtube regexp breaks the scenario of "go to youtube.com front page, click a video there". Yes, this changes the URL to /watch, but this happens through AJAX, not a regular page load and thus Play/Pause "misses" it.

So the regexp change needs to be reverted. Unless, of course, you know a better solution that catches dynamic loading.

Second, the design of the hotkey settings panel stands out significantly in comparison to the rest of the Firefox UI. Which is not bad per-se, but contradicts the general intent of Play/Pause to be maximally unobtrusive.

So what about using just a pair of preference values with "type: string" instead? Looks like it would work. Also looks simple enough, leaves my wondering why haven't I done this myself ages ago.

**Comment by DanielKamkha** [comment]
Yes, adding the button conditionally was the original idea. But youtube keeps changing its code constantly  so this broke at some point. Sadly, changing the regexp does not fix the issue, just pushes it elsewhere.

As for the hotkey, yes, the detection of key names is very nice. So let's keep the panel, I can adjust the style myself later.

**Comment by R0maric** [comment]
Ok, but we could add a hidden option (a turn on in about:config) to keep this regexp for those who like me off the AJAX loading on YouTube?

**Comment by DanielKamkha** [comment]
Let's not proliferate workarounds. I filed a bug to keep myself reminded: https://github.com/DanielKamkha/PlayPauseFirefox/issues/22. Will investigate it deeper later.

**Pull request merged**
